# Generated by Django 5.1.1 on 2025-01-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_userprofile_images_delete_userimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe/')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tryon/')),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.userimage')),
                ('wardrobe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.wardrobeitem')),
            ],
        ),
    ]
