# Generated by Django 5.1.1 on 2024-10-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='user', to='core.userimages'),
        ),
    ]
