# Generated by Django 5.1.1 on 2025-01-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='images',
        ),
        migrations.DeleteModel(
            name='UserImages',
        ),
    ]
