# Generated by Django 5.1.1 on 2024-10-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chat_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
