# Generated by Django 5.1.1 on 2025-04-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_message_content_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id']},
        ),
    ]
