# Generated by Django 5.1.1 on 2024-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
