# Generated by Django 5.1.1 on 2024-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_alter_virtualphotos_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
