# Generated by Django 5.1.1 on 2024-10-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('webstore', '0006_alter_productitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphotos',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='webstore.productitem'),
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_tryon', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='virtualphotos',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='webstore.virtualmodel'),
        ),
        migrations.AlterField(
            model_name='virtualphotos',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_photos', to='webstore.productitem'),
        ),
    ]
