# Generated by Django 5.1.1 on 2024-10-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0008_alter_virtualphotos_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualphotos',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='webstore.virtualmodel'),
        ),
    ]
