# Generated by Django 5.1.1 on 2025-04-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_images_delete_userimages'),
        ('webstore', '0009_alter_virtualphotos_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashsale',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='webstore.productitem'),
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tryon', to='core.userprofile'),
        ),
    ]
