# Generated by Django 5.1.1 on 2025-04-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_images_delete_userimages'),
        ('webstore', '0010_alter_flashsale_options_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='wardrobe/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to='core.userprofile')),
            ],
        ),
    ]
